// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

ng.module('uiDropkick.services').factory('dropkick', function() {
  var Model;
  Model = (function() {
    var getDefaults, getDropdownTemplate, getOptionTemplate, validData;

    function Model() {
      this.setTheme = __bind(this.setTheme, this);
    }

    Model.prototype.init = function(params) {};

    Model.prototype.getSettings = function() {};

    Model.prototype.getParams = function() {};

    Model.prototype.getTheme = function() {};

    Model.prototype.setTheme = function() {};

    Model.prototype.reset = function() {};


    /*
    				PRIVATE METHODS
     */

    Model.build = function() {
      var dropdown;
      dropdown = '';
      return dropdown;
    };

    getDropdownTemplate = function() {
      var dropdownTemplate;
      dropdownTemplate = ['<div class="dk_container" id="dk_container_{{ id }}" tabindex="{{ tabindex }}">', '<a class="dk_toggle">', '<span class="dk_label">{{ label }}</span>', '</a>', '<div class="dk_options">', '<ul class="dk_options_inner">', '</ul>', '</div>', '</div>'].join('');
      return dropdownTemplate;
    };

    getOptionTemplate = function() {
      var optionTemplate;
      optionTemplate = '<li class="{{ current }} {{ class}}"><a data-dk-dropdown-value="{{ value }}">{{ text }}</a></li>';
      return optionTemplate;
    };

    getDefaults = function() {
      var defaults;
      defaults = {
        startSpeed: 1000,
        theme: false,
        change: false,
        data: []
      };
      return defaults;
    };

    validData = function(data) {};

    return Model;

  })();
  return new Model;
});
