// Generated by CoffeeScript 1.7.1
ng.module('uiDropkick.services').factory('model', function() {

  /*
  			multilinecomments
   */
  var dropkickModel, getDropdownDefaults, getDropdownTemplate, getOptionTemplate;
  getDropdownTemplate = function() {
    var dropdownTemplate;
    dropdownTemplate = ['<div class="dk_container" id="dk_container_{{ id }}" tabindex="{{ tabindex }}">', '<a class="dk_toggle">', '<span class="dk_label">{{ label }}</span>', '</a>', '<div class="dk_options">', '<ul class="dk_options_inner">', '</ul>', '</div>', '</div>'].join('');
    return dropdownTemplate;
  };
  getOptionTemplate = function() {
    var optionTemplate;
    optionTemplate = '<li class="{{ current }}"><a data-dk-dropdown-value="{{ value }}">{{ text }}</a></li>';
    return optionTemplate;
  };
  getDropdownDefaults = function() {
    var defaults;
    defaults = {
      startSpeed: 1000,
      theme: false,
      change: false
    };
    return defaults;
  };
  return dropkickModel = function() {};
});
