// Generated by CoffeeScript 1.6.3
ng.module('uiDropkick.services').factory('dropkick', function() {
  var Model;
  Model = (function() {
    var getBaseSettings, self, validData;

    function Model() {}

    self = Model;

    Model.prototype.init = function(params) {
      return self.modelSettings = ng.extend(getBaseSettings(), params);
    };

    Model.prototype.getParams = function() {};

    Model.prototype.getTheme = function() {};

    Model.prototype.setTheme = function() {};

    Model.prototype.setScope = function(scope) {
      return self.modelSettings.$scope = scope;
    };

    Model.prototype.reset = function() {};

    /*
    				PRIVATE METHODS
    */


    getBaseSettings = function() {
      var defaults;
      defaults = {
        startSpeed: 1000,
        theme: false,
        change: false,
        reload: false,
        data: [],
        $scope: null
      };
      return defaults;
    };

    Model.modelSettings = {};

    validData = function(data) {};

    return Model;

  })();
  return new Model;
});
