// Generated by CoffeeScript 1.7.1
ng.module('ngDropkick.services', []);

ng.module('ngDropkick.controllers', []);

ng.module('ngDropkick.directives', []);

ng.module('ngDropkick.filters', []);

ng.module('ng-dropkick', ['ngDropkick.services', 'ngDropkick.controllers', 'ngDropkick.directives', 'ngDropkick.filters']);
