// Generated by CoffeeScript 1.6.3
ng.module('uiDropkick.directives').directive('ngDropkick', [
  'dropkick', function(model) {
    var dropkick;
    dropkick = {
      restrict: 'A',
      scope: true,
      controller: 'dropkickCtrl',
      compile: function() {
        return function(scope, elem, attrs, ctrl) {};
      }
    };
    return dropkick;
  }
]);
