// Generated by CoffeeScript 1.7.1
ng.module('uiDropkick.directives').directive('ngDropkick', function() {
  var dropkick;
  dropkick = {
    restrict: 'A',
    link: function(scope, elem, attrs) {
      return console.log(elem);
    }
  };
  return dropkick;
});
