// Generated by CoffeeScript 1.7.1
ng.module('uiDropkick.services', []);

ng.module('uiDropkick.controllers', []);

ng.module('uiDropkick.directives', []);

ng.module('uiDropkick.filters', []);

ng.module('uiDropkick', ['uiDropkick.services', 'uiDropkick.controllers', 'uiDropkick.directives', 'uiDropkick.filters']);
