// Generated by CoffeeScript 1.7.1
ng.module('uiDropkick.controllers').controller('dropkickCtrl', [
  '$scope', 'dropkick', function($scope, model) {
    var DropkickCtrl;
    model.setScope($scope);
    DropkickCtrl = (function() {
      function DropkickCtrl() {}

      DropkickCtrl.prototype.getDropdownTemplate = function() {
        var dropdownTemplate;
        dropdownTemplate = ['<div class="dk_container" id="dk_container_{{ id }}" tabindex="{{ tabindex }}">', '<a class="dk_toggle">', '<span class="dk_label">{{ label }}</span>', '</a>', '<div class="dk_options">', '<ul class="dk_options_inner">', '</ul>', '</div>', '</div>'].join('');
        return dropdownTemplate;
      };

      DropkickCtrl.prototype.getOptionTemplate = function() {
        var optionTemplate;
        optionTemplate = '<li class="{{ current }} {{ class}}"><a data-dk-dropdown-value="{{ value }}">{{ text }}</a></li>';
        return optionTemplate;
      };

      DropkickCtrl.prototype.build = function() {
        var dropkick;
        dropkick = '';
        return dropkick;
      };

      DropkickCtrl;

      return DropkickCtrl;

    })();
    return new DropkickCtrl;
  }
]);
