// Generated by CoffeeScript 1.7.1
var app, ng;

app = window.app || {};

'use strict';

ng = angular;

ng.module('module.services', []);

ng.module('module.controllers', []);

ng.module('module.directives', []);

ng.module('module.filters', []);

ng.module('ngDropkickApp', ['module.services', 'module.controllers', 'module.directives', 'module.filters', 'ng-dropkick']);
