// Generated by CoffeeScript 1.7.1
ng.module('module.controllers').controller('mainCtrl', [
  '$scope', 'dropkick', function($scope, dropkick) {
    $scope.items = [0, 1, 2, 3, 4, 5];
    return dropkick.init({
      data: $scope.items
    });
  }
]);
