// Generated by CoffeeScript 1.6.3
ng.module('module.controllers').controller('mainCtrl', [
  '$scope', 'dropkick', function($scope, dropkick) {
    $scope.items = [0, 1, 2, 3, 4, 5];
    return dropkick.init({
      data: $scope.items,
      change: function() {
        return console.log('change');
      },
      reload: function() {
        return console.log('reload');
      }
    });
  }
]);
